/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d0e9d6",
        "on-primary-fixed": "#0a2014",
        "primary-fixed-dim": "#b4ccbb",
        "tertiary": "#ffb4a9",
        "surface-container-high": "#282a2b",
        "error-container": "#93000a",
        "on-secondary-fixed": "#241a00",
        "on-primary": "#203529",
        "inverse-on-surface": "#2f3131",
        "surface-container-low": "#1a1c1c",
        "secondary": "#e9c349",
        "surface": "#121414",
        "outline": "#8c928c",
        "primary-container": "#1a2f23",
        "on-tertiary-fixed-variant": "#8e130c",
        "alert-red": "#C0392B",
        "primary": "#b4ccbb",
        "on-secondary-container": "#342800",
        "outline-variant": "#424843",
        "tertiary-fixed": "#ffdad5",
        "on-background": "#e2e2e2",
        "on-tertiary-container": "#f7604e",
        "background": "#121414",
        "on-error": "#690005",
        "inverse-surface": "#e2e2e2",
        "on-primary-fixed-variant": "#364c3e",
        "surface-tint": "#b4ccbb",
        "surface-dim": "#121414",
        "secondary-container": "#af8d11",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#ffb4a9",
        "tertiary-container": "#5e0001",
        "surface-container-highest": "#333535",
        "earth-gold": "#D4AF37",
        "surface-container-lowest": "#0c0f0f",
        "surface-variant": "#333535",
        "inverse-primary": "#4d6355",
        "surface-container": "#1e2020",
        "secondary-fixed": "#ffe088",
        "mist-white": "#F5F5F5",
        "surface-bright": "#38393a",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed-variant": "#574500",
        "on-error-container": "#ffdad6",
        "deep-forest": "#1A2F23",
        "on-primary-container": "#809787",
        "on-surface-variant": "#c2c8c2",
        "on-secondary": "#3c2f00",
        "on-surface": "#e2e2e2",
        "on-tertiary-fixed": "#410000",
        "on-tertiary": "#690001",
        "glass-overlay": "rgba(26, 47, 35, 0.75)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "organic": "12px",
        "2xl": "1.125rem",
      },
      spacing: {
        "max-content-width": "1440px",
        "gutter-md": "24px",
        "base": "8px",
        "gutter-sm": "16px",
        "margin-desktop": "40px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "bebas": ["Bebas Neue", "sans-serif"],
        "syne": ["Syne", "sans-serif"],
        "cinzel": ["Cinzel", "serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "headline-lg": ["Libre Caslon Text", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Libre Caslon Text", "serif"],
        "data-viz": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Libre Caslon Text", "serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "data-viz": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}